imports:
    - { resource: modules.yaml}

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    _instanceof:
        App\Shared\Application\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        
        App\Shared\Application\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
